Added script 1 as download_data.R and script 2 as preprocess_data.R
karlie-tr/dsci-310-group-03 pull request #105
Opened 2023-03-23 07:10 UTC by ngserjie

2023-03-23 07:37 UTC, anhndq01 commented on src/download_data.R
the file on line 4 should be download_data.R

2023-03-23 07:44 UTC, anhndq01 reviewed
I think we should modify the notebook using the new script as well.

2023-03-23 23:53 UTC, karlie-tr requested changes

2023-03-23 23:53 UTC, karlie-tr commented on results/training_set.csv
i think the format for this data frame is not what we expected. This is what it currently looks like from this script:
![image](https://user-images.githubusercontent.com/99240209/227389179-6cbe2575-85b8-4a53-b7a9-7463442c63b5.png)

i think it should look more like this:
![image](https://user-images.githubusercontent.com/99240209/227389428-49b6fd1b-4e4e-4af3-95b9-ca5cbf0b19ca.png)

2023-03-24 17:44 UTC, karlie-tr approved these changes

2023-03-24 17:44 UTC, merged